/* ============================================================================
 * QA Interview Mastery — Glossary
 * The complete QA vocabulary. window.QA_GLOSSARY is consumed by app.js.
 * Each term: { t: term, abbr?, cat: categoryId, d: definition }
 * ==========================================================================*/
(function () {
  "use strict";

  const categories = [
    { id: "found", name: "Foundations", icon: "🧱" },
    { id: "levels", name: "Test Levels", icon: "🔺" },
    { id: "types", name: "Test Types", icon: "🌳" },
    { id: "design", name: "Design Techniques", icon: "✏️" },
    { id: "defect", name: "Defect Management", icon: "🐞" },
    { id: "docs", name: "Artifacts & Docs", icon: "📄" },
    { id: "auto", name: "Automation", icon: "🤖" },
    { id: "api", name: "API & Backend", icon: "🔌" },
    { id: "perf", name: "Performance & Non-Functional", icon: "⚡" },
    { id: "cicd", name: "CI/CD & DevOps", icon: "🚦" },
    { id: "agile", name: "Agile & Process", icon: "🔁" },
    { id: "metrics", name: "Metrics", icon: "📈" },
    { id: "env", name: "Environments & Data", icon: "🗄️" },
    { id: "sec", name: "Security", icon: "🔒" },
  ];

  const terms = [
    /* ── Foundations ── */
    { t: "Quality Assurance", abbr: "QA", cat: "found", d: "A process-oriented, *preventive* discipline that builds the right processes, standards and reviews so defects are less likely to be introduced. Asks: 'are we doing things the right way?'" },
    { t: "Quality Control", abbr: "QC", cat: "found", d: "A product-oriented, *detective* activity that inspects the actual deliverable to find defects. Asks: 'did we build it right?' QC sits inside QA." },
    { t: "Testing", cat: "found", d: "The hands-on activity of executing software (manually or via automation) to find defects and verify behaviour. A subset of QC." },
    { t: "Verification", cat: "found", d: "'Are we building the product right?' — static checks (reviews, inspections, walkthroughs) that the product conforms to its specification, without executing code." },
    { t: "Validation", cat: "found", d: "'Are we building the right product?' — dynamic checks (executing the software) that it meets the user's actual needs." },
    { t: "Static Testing", cat: "found", d: "Examining work products without executing code — reviews, inspections, walkthroughs, and static analysis of source." },
    { t: "Dynamic Testing", cat: "found", d: "Testing that involves executing the software with inputs and checking outputs/behaviour." },
    { t: "Defect / Bug", cat: "found", d: "A flaw in the software that causes it to behave differently from the requirement or expectation. Caused by an error, manifests as a failure." },
    { t: "Error / Mistake", cat: "found", d: "A human action that produces an incorrect result — e.g. a developer's coding mistake that introduces a defect." },
    { t: "Fault", cat: "found", d: "The defect in code/design itself (the embedded flaw); the static cause that may lead to a failure when executed." },
    { t: "Failure", cat: "found", d: "The observable event where the system does not perform a required function — a defect, when triggered, produces a failure." },
    { t: "Root Cause", cat: "found", d: "The underlying reason a defect exists. Root Cause Analysis (RCA) traces a failure back to its origin to prevent recurrence." },
    { t: "Quality", cat: "found", d: "The degree to which software meets requirements and satisfies user needs — both conformance to spec and fitness for purpose." },
    { t: "SDLC", abbr: "Software Development Life Cycle", cat: "found", d: "The phased framework for building software: Requirements → Design → Development → Testing → Deployment → Maintenance." },
    { t: "STLC", abbr: "Software Testing Life Cycle", cat: "found", d: "The phased framework for testing: Requirement Analysis → Test Planning → Test Design → Environment Setup → Execution → Cycle Closure." },
    { t: "Waterfall Model", cat: "found", d: "A sequential SDLC where each phase completes before the next begins; testing happens late, after development." },
    { t: "V-Model", cat: "found", d: "A sequential model that pairs each development phase with a corresponding test level (e.g. requirements↔acceptance, design↔integration, coding↔unit)." },
    { t: "Agile Model", cat: "found", d: "An iterative, incremental SDLC delivering working software in short cycles, with continuous testing embedded throughout." },
    { t: "Shift-Left Testing", cat: "found", d: "Moving testing activities earlier in the SDLC (requirements/design) where defects are far cheaper to fix." },
    { t: "Shift-Right Testing", cat: "found", d: "Testing in production — canary releases, feature flags, observability, chaos engineering, synthetic monitoring — to learn from real usage." },
    { t: "Cost of Quality", cat: "found", d: "The total cost of preventing, finding and fixing defects. Defects get ~10× more expensive at each stage they escape." },

    /* ── Test Levels ── */
    { t: "Unit Testing", cat: "levels", d: "Testing the smallest testable piece (a function/class) in isolation, usually written by developers and run in milliseconds." },
    { t: "Component Testing", cat: "levels", d: "Testing an individual module/component in isolation (sometimes used interchangeably with unit testing)." },
    { t: "Integration Testing", cat: "levels", d: "Testing that combined modules or services work together correctly; catches interface and contract defects." },
    { t: "System Testing", cat: "levels", d: "Testing the fully integrated application end-to-end against the specified requirements." },
    { t: "Acceptance Testing", abbr: "UAT", cat: "levels", d: "Final validation by the business/end users that the software meets the real need; the gate to release." },
    { t: "End-to-End Testing", abbr: "E2E", cat: "levels", d: "Testing a complete user journey through the whole stack as a real user would experience it." },
    { t: "Big Bang Integration", cat: "levels", d: "Integrating all modules at once and testing together — risky, since locating defects is hard." },
    { t: "Incremental Integration", cat: "levels", d: "Integrating and testing modules step-by-step — top-down, bottom-up, or sandwich/hybrid." },

    /* ── Test Types ── */
    { t: "Functional Testing", cat: "types", d: "Verifies the system does what it should — every feature, input and business rule conforms to requirements." },
    { t: "Non-Functional Testing", cat: "types", d: "Verifies quality attributes — how well the system performs (speed, security, usability, reliability) rather than what it does." },
    { t: "Smoke Testing", cat: "types", d: "A wide, shallow check that a new build's critical paths work — 'build verification'. If it fails, reject the build." },
    { t: "Sanity Testing", cat: "types", d: "A narrow, deep check of a specific fix or feature after a minor change, to confirm it works before deeper testing." },
    { t: "Regression Testing", cat: "types", d: "Re-running existing tests to confirm that new changes haven't broken previously working functionality." },
    { t: "Re-testing / Confirmation Testing", cat: "types", d: "Verifying that a specific reported defect has actually been fixed (distinct from regression)." },
    { t: "Exploratory Testing", cat: "types", d: "Simultaneous learning, test design and execution, guided by the tester's intuition rather than scripted steps." },
    { t: "Ad-hoc Testing", cat: "types", d: "Informal, unstructured testing without documentation or planning, relying on tester knowledge to find defects." },
    { t: "Monkey Testing", cat: "types", d: "Feeding random inputs/actions to the system to see if it crashes — no test cases, fully random." },
    { t: "Acceptance Test (Alpha)", cat: "types", d: "Testing performed in-house by internal staff before release to external users." },
    { t: "Acceptance Test (Beta)", cat: "types", d: "Testing by real users in their own environment before general release, to gather real-world feedback." },
    { t: "Usability Testing", cat: "types", d: "Evaluating how easy, intuitive and satisfying the product is for real users to use." },
    { t: "Accessibility Testing", cat: "types", d: "Verifying the product is usable by people with disabilities, against standards such as WCAG (screen readers, contrast, keyboard nav)." },
    { t: "Compatibility Testing", cat: "types", d: "Checking the software works across different browsers, devices, OSes, screen sizes and configurations." },
    { t: "Cross-Browser Testing", cat: "types", d: "A form of compatibility testing focused on consistent behaviour across web browsers." },
    { t: "Localization Testing", abbr: "L10n", cat: "types", d: "Verifying the product is correctly adapted for a specific locale — language, currency, date formats, cultural norms." },
    { t: "Internationalization Testing", abbr: "I18n", cat: "types", d: "Verifying the product is built to support multiple locales without code changes (unicode, layout for RTL, etc.)." },
    { t: "Globalization Testing", cat: "types", d: "Ensuring software functions correctly across all target regions and languages worldwide." },
    { t: "GUI Testing", cat: "types", d: "Verifying the graphical user interface elements (layout, fonts, buttons, alignment) appear and behave correctly." },
    { t: "Backend Testing", cat: "types", d: "Testing the server-side: databases, APIs and business logic beneath the UI." },
    { t: "Database Testing", cat: "types", d: "Validating data integrity, CRUD operations, schema, stored procedures, triggers and constraints in the database." },

    /* ── Design Techniques ── */
    { t: "Black-Box Testing", cat: "design", d: "Testing based only on inputs/outputs and requirements, without knowledge of internal code." },
    { t: "White-Box Testing", cat: "design", d: "Testing based on internal code structure — covering statements, branches, paths and conditions." },
    { t: "Gray-Box Testing", cat: "design", d: "A hybrid using partial knowledge of internal structure (e.g. database schema, architecture) to design black-box tests." },
    { t: "Equivalence Partitioning", abbr: "EP", cat: "design", d: "Dividing inputs into classes that should behave identically and testing one representative per class to cut redundant cases." },
    { t: "Boundary Value Analysis", abbr: "BVA", cat: "design", d: "Testing at the edges of input ranges (min, min±1, max, max±1) where off-by-one defects cluster." },
    { t: "Decision Table Testing", cat: "design", d: "Mapping combinations of input conditions to expected actions — ideal for complex interacting business rules." },
    { t: "State Transition Testing", cat: "design", d: "Designing tests around the states a system can be in and the valid/invalid transitions between them." },
    { t: "Pairwise / All-Pairs Testing", cat: "design", d: "A combinatorial technique that covers all pairs of input values, drastically reducing cases vs. testing every combination." },
    { t: "Use Case Testing", cat: "design", d: "Deriving test cases from use cases — the end-to-end transactions a user performs with the system." },
    { t: "Error Guessing", cat: "design", d: "Using experience and intuition to anticipate where defects are likely (empty fields, zero, nulls, special chars)." },
    { t: "Cause-Effect Graphing", cat: "design", d: "A graphical technique linking causes (inputs) to effects (outputs) to derive a minimal set of high-yield test cases." },
    { t: "Statement Coverage", cat: "design", d: "A white-box metric: the percentage of executable statements exercised by the tests." },
    { t: "Branch / Decision Coverage", cat: "design", d: "A white-box metric: the percentage of decision branches (true/false outcomes) exercised by the tests." },
    { t: "Path Coverage", cat: "design", d: "A white-box metric: the percentage of independent execution paths through the code that tests exercise." },
    { t: "Code Coverage", cat: "design", d: "The proportion of source code executed by the test suite — a useful but not sufficient quality signal." },

    /* ── Defect Management ── */
    { t: "Defect Life Cycle", cat: "defect", d: "The states a defect passes through: New → Assigned → Open → Fixed → Retest → Verified → Closed, with branches for Reopened/Rejected/Duplicate/Deferred." },
    { t: "Severity", cat: "defect", d: "The technical impact of a defect on the system (Critical/High/Medium/Low). Owned by QA." },
    { t: "Priority", cat: "defect", d: "The business urgency to fix a defect (P1/P2/P3). Owned by Product/Release. Independent of severity." },
    { t: "Defect Triage", cat: "defect", d: "A meeting where stakeholders review defects to confirm validity and agree severity, priority and assignment." },
    { t: "Reopened", cat: "defect", d: "Defect status when a fix fails re-testing and the bug returns to the developer." },
    { t: "Deferred / Postponed", cat: "defect", d: "A valid defect that won't be fixed in the current release due to low priority or risk." },
    { t: "Duplicate", cat: "defect", d: "A defect already reported elsewhere; closed as a duplicate of the original." },
    { t: "Rejected / Not a Bug", cat: "defect", d: "A reported defect deemed invalid — works as designed, or a misunderstanding of requirements." },
    { t: "Known Issue", cat: "defect", d: "An accepted, documented defect shipped with the release, communicated to stakeholders/users." },
    { t: "Defect Density", cat: "defect", d: "Number of confirmed defects divided by size (per module, KLOC, or function point)." },
    { t: "Defect Age", cat: "defect", d: "The time a defect remains open from detection to closure." },
    { t: "Defect Clustering", cat: "defect", d: "The principle that a small number of modules usually contain most defects (a Pareto effect) — focus testing there." },
    { t: "Defect Leakage / Escape", cat: "defect", d: "Defects that slip past QA and are found in production — the key measure of testing effectiveness." },

    /* ── Artifacts & Docs ── */
    { t: "Test Strategy", cat: "docs", d: "A high-level, org/program-level document defining the overall approach to quality: scope, risk model, automation split, tooling, standards." },
    { t: "Test Plan", cat: "docs", d: "A project/release-specific document: scope, objectives, schedule, resources, deliverables, entry/exit criteria for this release." },
    { t: "Test Case", cat: "docs", d: "A documented set of preconditions, steps, test data and expected results to verify one specific behaviour." },
    { t: "Test Scenario", cat: "docs", d: "A high-level description of what to test (a feature/flow), from which detailed test cases are derived." },
    { t: "Test Script", cat: "docs", d: "A set of automated instructions (code) that executes a test case." },
    { t: "Test Suite", cat: "docs", d: "A collection of related test cases grouped for execution (e.g. a regression suite, smoke suite)." },
    { t: "Test Data", cat: "docs", d: "The specific inputs and dataset used to execute test cases (valid, invalid, boundary, edge)." },
    { t: "Test Bed", cat: "docs", d: "The combined environment configured for testing — hardware, software, network and data." },
    { t: "RTM", abbr: "Requirements Traceability Matrix", cat: "docs", d: "A document mapping each requirement to its test cases (and defects), exposing coverage gaps." },
    { t: "Entry Criteria", cat: "docs", d: "Conditions that must be met before a test phase can begin (e.g. build deployed, smoke passing, data ready)." },
    { t: "Exit Criteria", cat: "docs", d: "Conditions that must be met to stop testing and release (e.g. % executed, pass rate, zero open Sev-1/2)." },
    { t: "Definition of Done", abbr: "DoD", cat: "docs", d: "A shared checklist of what 'complete' means for a story — typically including tests written, passing, and code reviewed." },
    { t: "Definition of Ready", abbr: "DoR", cat: "docs", d: "Criteria a backlog item must meet before the team commits to it — clear acceptance criteria, testable, estimated." },
    { t: "Acceptance Criteria", cat: "docs", d: "The conditions a feature must satisfy to be accepted, often written as Gherkin Given/When/Then." },
    { t: "Test Summary Report", cat: "docs", d: "A closure document summarising what was tested, results, metrics, defects and residual risk." },
    { t: "Bug Report", cat: "docs", d: "A documented defect with title, environment, steps to reproduce, expected vs actual, severity, priority and evidence." },

    /* ── Automation ── */
    { t: "Test Automation", cat: "auto", d: "Using software/tools to execute tests, compare actual vs expected results and report — typically for regression." },
    { t: "Test Automation Pyramid", cat: "auto", d: "A model prescribing many fast unit tests, fewer integration/API tests, and few slow UI/E2E tests." },
    { t: "Ice-Cream Cone (Anti-pattern)", cat: "auto", d: "An inverted pyramid with too many UI tests and too few unit tests — slow, flaky, expensive." },
    { t: "Page Object Model", abbr: "POM", cat: "auto", d: "A design pattern where each page/component is a class exposing behaviours and hiding locators, so UI changes touch one place." },
    { t: "Locator / Selector", cat: "auto", d: "How automation finds an element on a page (ID, CSS, XPath, data-testid). Stable locators reduce flakiness." },
    { t: "Implicit Wait", cat: "auto", d: "A global setting telling the driver to poll for an element up to a timeout before failing." },
    { t: "Explicit Wait", cat: "auto", d: "Waiting for a specific condition on a specific element (clickable, visible) — the recommended, precise approach." },
    { t: "Fluent Wait", cat: "auto", d: "An explicit wait with a custom polling interval and ignored exceptions." },
    { t: "Flaky Test", cat: "auto", d: "A test that passes and fails non-deterministically on the same code — usually due to bad waits, shared state or races." },
    { t: "Test Quarantine", cat: "auto", d: "Isolating flaky tests out of the blocking pipeline so they don't erode trust, while they're fixed or deleted." },
    { t: "Data-Driven Testing", abbr: "DDT", cat: "auto", d: "Running the same test logic against multiple data sets stored externally (CSV, Excel, JSON)." },
    { t: "Keyword-Driven Testing", cat: "auto", d: "A framework where tests are built from reusable keywords/actions, separating logic from test design." },
    { t: "BDD", abbr: "Behaviour-Driven Development", cat: "auto", d: "Writing executable specs in plain language (Gherkin Given/When/Then) shared by business, dev and QA." },
    { t: "TDD", abbr: "Test-Driven Development", cat: "auto", d: "Writing a failing test first, then the minimal code to pass it, then refactoring (red-green-refactor)." },
    { t: "Headless Testing", cat: "auto", d: "Running browser tests without a visible UI, for speed in CI." },
    { t: "Cross-Browser Grid", cat: "auto", d: "Infrastructure (e.g. Selenium Grid) to run tests in parallel across many browser/OS combinations." },
    { t: "Visual Regression Testing", cat: "auto", d: "Comparing screenshots against a baseline to catch unintended visual/UI changes." },
    { t: "Selenium", cat: "auto", d: "A widely-used open-source framework for automating web browsers via the WebDriver protocol." },
    { t: "Playwright / Cypress", cat: "auto", d: "Modern web automation frameworks with auto-waiting, fast execution and strong debugging." },

    /* ── API & Backend ── */
    { t: "API", abbr: "Application Programming Interface", cat: "api", d: "A contract by which software components communicate; QA tests endpoints directly, below the UI." },
    { t: "REST", cat: "api", d: "An architectural style for web APIs using HTTP methods (GET/POST/PUT/DELETE) and resources." },
    { t: "Endpoint", cat: "api", d: "A specific URL/path on an API that performs an operation (e.g. /api/orders/42)." },
    { t: "HTTP Status Code", cat: "api", d: "A 3-digit code indicating request outcome: 2xx success, 3xx redirect, 4xx client error, 5xx server error." },
    { t: "Idempotency", cat: "api", d: "A property where repeating the same request produces the same result (GET/PUT/DELETE are idempotent; POST is not)." },
    { t: "Payload / Body", cat: "api", d: "The data sent in a request or returned in a response, typically JSON or XML." },
    { t: "Contract Testing", cat: "api", d: "Verifying a consumer and provider agree on the API interface independently (e.g. Pact), avoiding full E2E." },
    { t: "Schema Validation", cat: "api", d: "Asserting an API response matches an expected structure/types (e.g. against an OpenAPI/JSON Schema)." },
    { t: "OpenAPI / Swagger", cat: "api", d: "A standard for describing REST APIs; used to generate docs, mocks and validate responses." },
    { t: "Authentication", cat: "api", d: "Verifying who a user is (login, tokens). 401 = not authenticated." },
    { t: "Authorization", cat: "api", d: "Verifying what an authenticated user is allowed to do. 403 = authenticated but forbidden." },
    { t: "OAuth / JWT", cat: "api", d: "Standards for delegated authorization and stateless tokens; QA tests acquisition, expiry, refresh and tampering." },
    { t: "Mocking / Stubbing", cat: "api", d: "Replacing a real dependency with a controlled fake to test a component in isolation." },
    { t: "Service Virtualization", cat: "api", d: "Simulating unavailable or costly third-party services (e.g. WireMock) so testing isn't blocked." },
    { t: "ACID", cat: "api", d: "Database transaction guarantees: Atomicity, Consistency, Isolation, Durability — key for data-integrity testing." },
    { t: "CRUD", cat: "api", d: "The four basic data operations: Create, Read, Update, Delete." },

    /* ── Performance & Non-Functional ── */
    { t: "Performance Testing", cat: "perf", d: "Evaluating speed, responsiveness and stability under a given workload." },
    { t: "Load Testing", cat: "perf", d: "Testing at expected concurrent load to verify response time and throughput meet SLAs." },
    { t: "Stress Testing", cat: "perf", d: "Pushing beyond capacity to find the breaking point and observe failure mode (graceful vs crash)." },
    { t: "Spike Testing", cat: "perf", d: "Applying a sudden sharp surge in load to test autoscaling and recovery." },
    { t: "Soak / Endurance Testing", cat: "perf", d: "Sustained load over hours/days to expose memory leaks and resource exhaustion." },
    { t: "Volume Testing", cat: "perf", d: "Testing with large volumes of data to evaluate database and query performance." },
    { t: "Scalability Testing", cat: "perf", d: "Verifying capacity grows appropriately as resources are added." },
    { t: "Throughput", cat: "perf", d: "The number of transactions/requests the system processes per unit time." },
    { t: "Latency / Response Time", cat: "perf", d: "The time taken to respond to a request; report percentiles (p95, p99), not just averages." },
    { t: "Percentile (p95/p99)", cat: "perf", d: "A value below which a given % of measurements fall — p99 latency = the experience of the slowest 1% of users." },
    { t: "SLA / SLO / SLI", cat: "perf", d: "Service Level Agreement (the promise), Objective (the target) and Indicator (the measured metric)." },
    { t: "Bottleneck", cat: "perf", d: "The component limiting overall performance (slow query, lock contention, connection-pool exhaustion)." },
    { t: "Reliability Testing", cat: "perf", d: "Verifying the system performs failure-free for a specified period under stated conditions." },
    { t: "Recovery Testing", cat: "perf", d: "Verifying the system recovers gracefully from crashes, network loss and hardware failure." },
    { t: "Failover Testing", cat: "perf", d: "Verifying the system switches to a backup/redundant system without data loss when a component fails." },
    { t: "Chaos Engineering", cat: "perf", d: "Deliberately injecting failures in production-like environments to test resilience." },

    /* ── CI/CD & DevOps ── */
    { t: "Continuous Integration", abbr: "CI", cat: "cicd", d: "Frequently merging code into a shared branch, with automated build and tests on every change." },
    { t: "Continuous Delivery", abbr: "CD", cat: "cicd", d: "Keeping software always in a releasable state through automated pipelines; release is a manual decision." },
    { t: "Continuous Deployment", cat: "cicd", d: "Automatically deploying every change that passes the pipeline to production, with no manual gate." },
    { t: "Pipeline", cat: "cicd", d: "An automated sequence of stages (build, test, deploy) a change passes through, ordered fast-to-slow." },
    { t: "Quality Gate", cat: "cicd", d: "An automated pass/fail checkpoint (e.g. coverage ≥ 80%, zero new critical issues) that blocks promotion if unmet." },
    { t: "Build Verification Test", abbr: "BVT", cat: "cicd", d: "An automated smoke suite run on each build to confirm it's stable enough for further testing." },
    { t: "Canary Release", cat: "cicd", d: "Rolling out a change to a small subset of users first, monitoring, then expanding if healthy." },
    { t: "Blue-Green Deployment", cat: "cicd", d: "Running two identical environments and switching traffic between them for zero-downtime releases and instant rollback." },
    { t: "Feature Flag / Toggle", cat: "cicd", d: "A switch to enable/disable a feature at runtime without deploying — enabling safe releases and testing in prod." },
    { t: "Rollback", cat: "cicd", d: "Reverting to a previous known-good version when a release causes problems." },
    { t: "Observability", cat: "cicd", d: "Understanding system state from its outputs — logs, metrics and traces — to detect and diagnose issues." },
    { t: "Synthetic Monitoring", cat: "cicd", d: "Running scripted transactions against production continuously to detect issues before users do." },
    { t: "DORA Metrics", cat: "cicd", d: "Four delivery-performance metrics: deployment frequency, lead time for changes, change failure rate, MTTR." },

    /* ── Agile & Process ── */
    { t: "Agile", cat: "agile", d: "An iterative philosophy valuing working software, collaboration and responding to change over rigid plans." },
    { t: "Scrum", cat: "agile", d: "An Agile framework delivering work in fixed-length sprints with defined roles, events and artifacts." },
    { t: "Kanban", cat: "agile", d: "A flow-based method visualising work on a board and limiting work-in-progress (WIP) to improve throughput." },
    { t: "Sprint / Iteration", cat: "agile", d: "A fixed time-box (1–4 weeks) in which a team delivers a potentially shippable increment." },
    { t: "User Story", cat: "agile", d: "A short feature description from the user's perspective: 'As a [role], I want [goal], so that [benefit].'" },
    { t: "Epic", cat: "agile", d: "A large body of work broken down into multiple user stories." },
    { t: "Backlog", cat: "agile", d: "The prioritised list of all work (stories, bugs, tasks) to be done." },
    { t: "Backlog Refinement / Grooming", cat: "agile", d: "Reviewing and sharpening backlog items — clarifying, estimating and making them testable before a sprint." },
    { t: "Three Amigos", cat: "agile", d: "A refinement conversation between Product, Development and QA to clarify a story from three perspectives." },
    { t: "Sprint Planning", cat: "agile", d: "The event where the team selects and plans the work for the upcoming sprint." },
    { t: "Daily Stand-up / Scrum", cat: "agile", d: "A short daily sync where the team shares progress, plans and blockers." },
    { t: "Sprint Review / Demo", cat: "agile", d: "Showing the completed increment to stakeholders for feedback at the end of a sprint." },
    { t: "Retrospective", cat: "agile", d: "A meeting where the team reflects on the sprint and agrees process improvements." },
    { t: "Velocity", cat: "agile", d: "The amount of work (story points) a team completes per sprint, used for forecasting." },
    { t: "Story Points", cat: "agile", d: "A relative estimate of effort/complexity for a story, often on a Fibonacci scale." },
    { t: "Burndown Chart", cat: "agile", d: "A graph showing remaining work over time in a sprint or release." },
    { t: "Whole-Team Quality", cat: "agile", d: "The principle that quality is everyone's responsibility — devs write tests, QA enables rather than gatekeeps." },

    /* ── Metrics ── */
    { t: "Defect Removal Efficiency", abbr: "DRE", cat: "metrics", d: "Defects found before release ÷ total defects. Higher is better; aim > 90%." },
    { t: "Test Coverage", cat: "metrics", d: "The proportion of requirements, code or risk exercised by tests." },
    { t: "Test Pass Rate", cat: "metrics", d: "The percentage of executed test cases that passed." },
    { t: "Test Execution Rate", cat: "metrics", d: "The percentage of planned test cases that have been executed." },
    { t: "Mean Time To Detect", abbr: "MTTD", cat: "metrics", d: "Average time taken to discover a defect or incident after it's introduced." },
    { t: "Mean Time To Resolve/Repair", abbr: "MTTR", cat: "metrics", d: "Average time taken to fix a defect or restore service after detection." },
    { t: "Mean Time Between Failures", abbr: "MTBF", cat: "metrics", d: "Average operating time between system failures — a reliability metric." },
    { t: "Escaped Defects", cat: "metrics", d: "Defects found in production — the single best severity-weighted measure of QA effectiveness." },
    { t: "Vanity Metric", cat: "metrics", d: "A metric that looks impressive but doesn't reflect outcomes (e.g. raw test-case or bug counts)." },
    { t: "Cyclomatic Complexity", cat: "metrics", d: "A measure of the number of independent paths through code — higher complexity needs more tests." },

    /* ── Environments & Data ── */
    { t: "Test Environment", cat: "env", d: "A configured setup (hardware, software, network, data) that mirrors production for testing." },
    { t: "DEV / QA / Staging / Prod", cat: "env", d: "The typical environment progression: development → testing → production-like staging → live production." },
    { t: "Staging Environment", cat: "env", d: "A production-like environment for final validation before release." },
    { t: "Ephemeral Environment", cat: "env", d: "A short-lived environment spun up per pull request/branch for isolated testing, then torn down." },
    { t: "Test Data Management", abbr: "TDM", cat: "env", d: "Creating, maintaining and provisioning the right test data — generated, masked or subsetted — for reliable tests." },
    { t: "Data Masking / Anonymization", cat: "env", d: "Replacing sensitive production data (PII) with realistic but fake values to comply with privacy laws." },
    { t: "Environment Parity", cat: "env", d: "Keeping lower environments as close to production as possible to avoid 'works in staging' surprises." },
    { t: "Containerization", cat: "env", d: "Packaging an app and its dependencies (e.g. Docker) for consistent, reproducible environments." },
    { t: "Test Fixture", cat: "env", d: "A fixed baseline state/data set up before tests run to ensure consistency and repeatability." },

    /* ── Security ── */
    { t: "Security Testing", cat: "sec", d: "Verifying the system protects data and resists attack — confidentiality, integrity, availability." },
    { t: "OWASP Top 10", cat: "sec", d: "A standard list of the most critical web application security risks, used to guide security testing." },
    { t: "SQL Injection", cat: "sec", d: "An injection attack where malicious SQL is inserted via input; prevented by parameterised queries." },
    { t: "Cross-Site Scripting", abbr: "XSS", cat: "sec", d: "Injecting malicious scripts that execute in other users' browsers; prevented by output encoding/sanitisation." },
    { t: "CSRF", abbr: "Cross-Site Request Forgery", cat: "sec", d: "Tricking an authenticated user's browser into making an unwanted request; prevented by anti-CSRF tokens." },
    { t: "IDOR", abbr: "Insecure Direct Object Reference", cat: "sec", d: "Broken object-level authorization — accessing another user's resource by changing an ID. The face of broken access control." },
    { t: "Broken Access Control", cat: "sec", d: "Failures enforcing what authenticated users may do — OWASP's #1 risk (privilege escalation, IDOR, forced browsing)." },
    { t: "Penetration Testing", cat: "sec", d: "Authorised simulated attacks to find and exploit vulnerabilities before real attackers do." },
    { t: "SAST / DAST", cat: "sec", d: "Static Application Security Testing (analysing source) and Dynamic (testing the running app) — often automated in CI." },
    { t: "Vulnerability", cat: "sec", d: "A weakness that can be exploited to compromise security (e.g. an outdated library, weak config)." },
  ];

  window.QA_GLOSSARY = { categories, terms };
})();
