/* ============================================================================
 * QA Interview Mastery — Catalog of Testing Types
 * "Every kind of testing", organized by category.
 * window.QA_TYPES is consumed by app.js -> types() view.
 * Each: { t, cat, d, long, when, how, tip, eg?, related:[names] }
 *   d    = one-line definition (card)
 *   long = deeper explanation (modal)
 *   when = when to use it
 *   how  = how it's performed
 *   tip  = practical / interview tip
 *   related = exact names of related types (clickable in modal)
 * ==========================================================================*/
(function () {
  "use strict";

  const categories = [
    { id: "approach", name: "By Approach & Method", icon: "🧭" },
    { id: "levels", name: "By Test Level", icon: "🔺" },
    { id: "functional", name: "Functional Testing", icon: "⚙️" },
    { id: "nonfunc", name: "Non-Functional Testing", icon: "📊" },
    { id: "perf", name: "Performance Testing", icon: "⚡" },
    { id: "security", name: "Security Testing", icon: "🔒" },
    { id: "change", name: "Maintenance & Change", icon: "🔧" },
    { id: "dev", name: "Development-Driven", icon: "🧪" },
    { id: "specialized", name: "Specialized & Modern", icon: "🚀" },
    { id: "domain", name: "Domain / Platform-Specific", icon: "📱" },
  ];

  const types = [
    /* ── By Approach & Method ── */
    { t: "Black-Box Testing", cat: "approach", d: "Testing from requirements via inputs/outputs only, with no knowledge of internal code.",
      long: "The tester treats the system as an opaque box: feed inputs, observe outputs, and compare against the specification — caring only about *what* the system does, not *how*. Most functional and system-level testing is black-box.",
      when: "Validating features against requirements/acceptance criteria, or when you don't have (or shouldn't rely on) source access.",
      how: "Apply design techniques — equivalence partitioning, boundary value analysis, decision tables, state transitions — to derive cases from the spec.",
      tip: "Interviewers love: 'black-box finds gaps between spec and behaviour; it can't tell you which code paths went untested' — that's white-box's job.",
      related: ["White-Box Testing", "Gray-Box Testing", "Exploratory Testing"] },
    { t: "White-Box Testing", cat: "approach", d: "Testing based on internal code structure — exercising statements, branches, conditions and paths.",
      long: "Also called structural or glass-box testing. The tester uses knowledge of the code to design tests that cover specific internal paths, ensuring logic, loops and branches are exercised.",
      when: "Unit testing, security review, and anywhere you need to measure/improve code coverage.",
      how: "Target coverage criteria: statement, branch/decision, condition, and path coverage; use a coverage tool to find untested code.",
      tip: "High coverage ≠ good tests — you can cover a line without asserting anything meaningful. Coverage is necessary, not sufficient.",
      related: ["Black-Box Testing", "Unit Testing", "Mutation Testing"] },
    { t: "Gray-Box Testing", cat: "approach", d: "A hybrid using partial internal knowledge (e.g. DB schema, architecture) to design better black-box tests.",
      long: "Combines black-box and white-box: the tester knows some internals (data model, APIs, architecture) and uses that to craft sharper end-to-end tests and verify back-end state.",
      when: "Integration, API and data-validation testing where checking the database confirms what the UI shows.",
      how: "Drive the UI/API, then verify the resulting state in logs or the database with a query.",
      tip: "UI-to-DB verification is the classic gray-box move: prove the screen value with SQL against the source of truth.",
      related: ["Black-Box Testing", "White-Box Testing", "Database Testing"] },
    { t: "Static Testing", cat: "approach", d: "Examining work products without executing code — reviews, walkthroughs, inspections, and static analysis.",
      long: "Defects are found by *reading* and *analysing* artifacts rather than running them. It catches issues early and cheaply, including in requirements before any code exists.",
      when: "Throughout development — requirement reviews, design reviews, code reviews, and automated linting in CI.",
      how: "Formal inspections, peer reviews, walkthroughs, and static-analysis tools (linters, SonarQube).",
      tip: "It's the purest form of shift-left: a requirement defect caught in review costs a fraction of one caught in production.",
      related: ["Dynamic Testing", "Maintenance Testing", "Behavior-Driven Development (BDD)"] },
    { t: "Dynamic Testing", cat: "approach", d: "Testing that executes the software with inputs and verifies the actual behaviour/output.",
      long: "The complement of static testing: you actually run the system and observe behaviour. Almost all functional and non-functional testing is dynamic.",
      when: "Any time you need to confirm runtime behaviour, performance or integration.",
      how: "Execute test cases (manual or automated) and compare actual vs expected results.",
      tip: "Static + dynamic together give the best coverage: read for early defects, run for behavioural ones.",
      related: ["Static Testing", "Manual Testing", "Automated Testing"] },
    { t: "Manual Testing", cat: "approach", d: "A human executes test cases and judges results, without automation tools.",
      long: "A person interacts with the application, following (or improvising) steps and using judgement to evaluate results — irreplaceable for UX, look-and-feel and exploration.",
      when: "Exploratory, usability and ad-hoc testing; one-off checks; rapidly changing UIs where automation isn't yet worthwhile.",
      how: "Execute documented cases or charters; observe, compare to expectations, and log defects with evidence.",
      tip: "Don't frame manual vs automated as rivals — humans explore and judge; automation guards known regressions.",
      related: ["Automated Testing", "Exploratory Testing", "Usability Testing"] },
    { t: "Automated Testing", cat: "approach", d: "Tools/scripts execute tests, compare results and report — ideal for repetitive regression.",
      long: "Tests are codified so a machine runs them quickly and repeatedly, especially in CI. A regression-protection investment that pays off over many runs.",
      when: "Stable, repetitive, high-value regression; data-driven checks; anything run on every build.",
      how: "Build a layered framework (e.g. Page Object Model), use explicit waits, keep tests atomic and parallel-safe.",
      tip: "Don't automate throwaway or highly volatile tests — negative ROI. Automate the stable regression core.",
      related: ["Manual Testing", "Continuous Testing", "Data-Driven Testing"] },
    { t: "Positive Testing", cat: "approach", d: "Feeding valid, expected inputs to confirm the system works as intended ('happy path').",
      long: "Verifies the system does the right thing when used correctly — the baseline that a feature functions at all.",
      when: "Always, as the first pass on any feature before probing edges and errors.",
      how: "Supply valid data within allowed ranges and confirm correct outputs and state changes.",
      tip: "Necessary but not enough — a feature that only passes the happy path is barely tested.",
      related: ["Negative Testing", "Boundary Value Testing", "Functional Testing"] },
    { t: "Negative Testing", cat: "approach", d: "Feeding invalid/unexpected inputs to confirm the system fails gracefully and validates correctly.",
      long: "Deliberately misuses the system — wrong types, empty fields, out-of-range values, malformed payloads — to confirm robust validation and clear error handling.",
      when: "After the happy path is confirmed; critical for forms, APIs and security.",
      how: "Use error guessing and boundary analysis to craft inputs that *should* be rejected, then verify graceful handling.",
      tip: "Most real-world bugs live off the happy path — strong negative testing is a senior signal.",
      related: ["Positive Testing", "Boundary Value Testing", "Fuzz Testing (Fuzzing)"] },
    { t: "Exploratory Testing", cat: "approach", d: "Simultaneous learning, test design and execution guided by tester intuition rather than scripts.",
      long: "The tester learns the product, designs and runs tests, and adapts — all at once. Excellent at finding bugs scripts can't anticipate.",
      when: "New/changed features, risk areas, and to complement automation's blind spots.",
      how: "Use Session-Based Test Management: time-boxed sessions with a written charter, notes and a debrief.",
      tip: "Keep it disciplined with charters and heuristics — exploratory is structured curiosity, not random clicking.",
      related: ["Ad-hoc Testing", "Manual Testing", "Risk-Based Testing"] },
    { t: "Ad-hoc Testing", cat: "approach", d: "Informal, unstructured testing without documentation, relying on tester experience to find defects.",
      long: "Spontaneous testing with no plan or cases — pure tester intuition. Useful for quick defect discovery but not repeatable.",
      when: "A fast sanity probe, or hunting in an area you suspect is fragile.",
      how: "Just use the application creatively, trying things a structured plan might skip.",
      tip: "Unlike exploratory testing, ad-hoc has no charter or notes — great for finds, poor for coverage evidence.",
      related: ["Exploratory Testing", "Monkey Testing", "Sanity Testing"] },
    { t: "Monkey Testing", cat: "approach", d: "Feeding random inputs/actions to see whether the system crashes — fully random, no test cases.",
      long: "Random, unstructured input (often automated) thrown at the app to uncover crashes and unexpected failures. 'Smart monkeys' know a bit about the app; 'dumb monkeys' are fully random.",
      when: "Robustness/stability checks, especially on mobile and UI stress.",
      how: "Use tools (e.g. Android Monkey) to generate random events, or manually bash inputs.",
      tip: "Great for finding crashes and memory issues; poor at finding logic bugs.",
      related: ["Gorilla Testing", "Fuzz Testing (Fuzzing)", "Ad-hoc Testing"] },
    { t: "Gorilla Testing", cat: "approach", d: "Hammering a single module repeatedly and intensively to confirm its robustness.",
      long: "Focuses intense, repeated testing on one module/function to break it — 'torture testing' a single area.",
      when: "When one component is critical or suspected fragile and needs hardening.",
      how: "Repeatedly exercise the same module with varied inputs until confident it holds.",
      tip: "Differs from monkey testing: gorilla is focused and intense on one area, not random across the app.",
      related: ["Monkey Testing", "Stress Testing", "Negative Testing"] },
    { t: "Pair Testing", cat: "approach", d: "Two people (often tester + developer) testing the same feature together at one workstation.",
      long: "Two minds on one screen — one drives, one observes and suggests — combining perspectives to find more and learn faster.",
      when: "Complex features, onboarding, or dev+QA collaboration in-sprint.",
      how: "Sit together, alternate driver/navigator roles, capture findings jointly.",
      tip: "Pairs a tester's edge-case instinct with a developer's internal knowledge — high defect yield per hour.",
      related: ["Exploratory Testing", "Manual Testing", "Agile Testing"] },

    /* ── By Test Level ── */
    { t: "Unit Testing", cat: "levels", d: "Testing the smallest testable unit (function/class) in isolation; usually written by developers.",
      long: "The base of the test pyramid — fast, isolated, cheap tests that pin down a single unit's behaviour, with dependencies mocked/stubbed.",
      when: "On every function/class as it's written; run on every commit in CI.",
      how: "Use a unit framework (JUnit, pytest, Jest); follow Arrange-Act-Assert; mock external dependencies.",
      tip: "Push verification down to units wherever possible — they localize failures instantly and run in milliseconds.",
      related: ["Component Testing", "Integration Testing", "Test-Driven Development (TDD)"] },
    { t: "Component Testing", cat: "levels", d: "Testing an individual module/component in isolation (often used interchangeably with unit testing).",
      long: "Tests a self-contained component (which may span several units) in isolation, using stubs/drivers for its collaborators.",
      when: "Verifying a module's behaviour before integrating it with others.",
      how: "Isolate the component with test doubles; exercise its public interface.",
      tip: "Some teams distinguish component (a deployable module) from unit (a single function) — clarify the definition in interviews.",
      related: ["Unit Testing", "Integration Testing", "Contract Testing"] },
    { t: "Integration Testing", cat: "levels", d: "Verifying that combined modules/services work together correctly; catches interface and contract defects.",
      long: "Focuses on the seams between components — data passing, interface contracts, and interactions that unit tests miss because they're isolated.",
      when: "After units pass, to confirm they cooperate; central in microservice architectures.",
      how: "Combine modules incrementally (top-down, bottom-up, sandwich) or all at once (big bang); verify data flow across boundaries.",
      tip: "Most 'it worked in isolation but broke together' bugs are interface mismatches — exactly what this level targets.",
      related: ["Big Bang Integration", "System Integration Testing", "Contract Testing"] },
    { t: "Big Bang Integration", cat: "levels", d: "Integrating all modules at once then testing together — fast to set up but hard to localize defects.",
      long: "All components are combined simultaneously and tested as a whole. Simple to start, but when something fails it's hard to pinpoint which interface broke.",
      when: "Small systems, or when all modules happen to be ready together.",
      how: "Assemble the full system, then run integration tests across it.",
      tip: "Avoid for large systems — incremental integration localizes defects far better.",
      related: ["Integration Testing", "Top-Down Integration", "Bottom-Up Integration"] },
    { t: "Top-Down Integration", cat: "levels", d: "Integrating from top-level modules downward, using stubs for lower modules not yet ready.",
      long: "Begins with high-level control modules and integrates downward, replacing not-yet-built lower modules with stubs.",
      when: "When top-level architecture is ready first and you want early end-to-end skeletons.",
      how: "Integrate the top module, stub its dependencies, then progressively replace stubs with real modules.",
      tip: "Validates high-level design and control flow early, but low-level modules get tested late.",
      related: ["Bottom-Up Integration", "Sandwich / Hybrid Integration", "Integration Testing"] },
    { t: "Bottom-Up Integration", cat: "levels", d: "Integrating from low-level modules upward, using drivers to simulate higher-level callers.",
      long: "Starts with the lowest-level modules and works up, using test drivers to simulate the modules that will eventually call them.",
      when: "When foundational/utility modules are built first.",
      how: "Integrate low-level modules, write drivers to invoke them, then add higher layers.",
      tip: "Low-level modules are well tested early, but you can't see the full system until late.",
      related: ["Top-Down Integration", "Sandwich / Hybrid Integration", "Integration Testing"] },
    { t: "Sandwich / Hybrid Integration", cat: "levels", d: "Combining top-down and bottom-up integration, meeting in the middle layer.",
      long: "Integrates from both ends simultaneously toward a target middle layer, using both stubs and drivers — balancing the trade-offs of each pure approach.",
      when: "Large layered systems where you want parallel progress from both ends.",
      how: "Run top-down and bottom-up in parallel, converging on the middle.",
      tip: "Most realistic for big systems, but needs more stubs+drivers and coordination.",
      related: ["Top-Down Integration", "Bottom-Up Integration", "Integration Testing"] },
    { t: "System Testing", cat: "levels", d: "Testing the fully integrated application end-to-end against the specified requirements.",
      long: "Black-box testing of the complete, integrated system in a production-like environment, validating both functional and non-functional requirements as a whole.",
      when: "After integration, before acceptance — the last QA-owned validation of the whole product.",
      how: "Execute end-to-end scenarios covering business workflows on the full stack.",
      tip: "It's the first level testing the *whole* product as the user will see it — broad in scope.",
      related: ["End-to-End Testing", "System Integration Testing", "Acceptance Testing (UAT)"] },
    { t: "System Integration Testing", cat: "levels", d: "Verifying interactions between the system and external/third-party systems and interfaces.",
      long: "SIT checks that your system correctly exchanges data with external systems (payment gateways, ERPs, partners) across real interfaces and protocols.",
      when: "When the product depends on external integrations and end-to-end data must flow correctly.",
      how: "Test against real or virtualized external systems; validate message formats, error handling and reconciliation.",
      tip: "Service virtualization keeps SIT unblocked when a third-party system is unavailable or costly.",
      related: ["Integration Testing", "Interface Testing", "Contract Testing"] },
    { t: "End-to-End Testing", cat: "levels", d: "Testing a complete real-world user journey across the whole stack as a user would experience it.",
      long: "Validates an entire workflow — UI, services, database, integrations — exactly as a user flows through it. High confidence, but slow and brittle, so reserve it for critical paths.",
      when: "A handful of business-critical journeys (login → purchase → confirmation).",
      how: "Automate with tools like Playwright/Cypress/Selenium against a full environment.",
      tip: "Keep E2E at the thin tip of the pyramid — too many makes a slow, flaky suite (the ice-cream-cone anti-pattern).",
      related: ["System Testing", "Smoke Testing", "Automated Testing"] },
    { t: "Acceptance Testing (UAT)", cat: "levels", d: "Final validation by business/end users that the software meets the real need; the gate to release.",
      long: "User Acceptance Testing confirms the software solves the actual business problem and is fit for purpose — owned by users/business, not QA.",
      when: "The final phase before go-live, after system testing passes.",
      how: "Business users run real-world scenarios against acceptance criteria and sign off.",
      tip: "QA enables UAT (data, scenarios, environment) but the *business* owns the accept/reject decision.",
      related: ["Alpha Testing", "Beta Testing", "Operational Acceptance Testing"] },
    { t: "Alpha Testing", cat: "levels", d: "Acceptance testing performed in-house by internal staff before external release.",
      long: "Conducted at the developer's site by internal teams (often a separate QA/UAT group) simulating real usage before any external users see it.",
      when: "Late in development, just before beta.",
      how: "Internal users exercise the near-final product in a controlled environment and report issues.",
      tip: "Alpha = internal, controlled site; Beta = external, real environment. Classic pairing question.",
      related: ["Beta Testing", "Acceptance Testing (UAT)", "Operational Acceptance Testing"] },
    { t: "Beta Testing", cat: "levels", d: "Testing by real users in their own environment before general release, to gather real-world feedback.",
      long: "Real customers use the product in their own environments and report bugs and feedback — surfacing issues that controlled testing can't (devices, networks, real data).",
      when: "After alpha, before general availability.",
      how: "Release to a limited external audience; collect feedback, crash reports and analytics.",
      tip: "A form of acceptance testing in the wild — invaluable for real-world compatibility and UX signals.",
      related: ["Alpha Testing", "Canary Testing", "Acceptance Testing (UAT)"] },
    { t: "Operational Acceptance Testing", cat: "levels", d: "Validating operational readiness — backups, recovery, maintenance, security procedures (OAT).",
      long: "OAT (a.k.a. operational readiness) checks the system is ready to *run* in production: backup/restore, failover, monitoring, maintenance and support procedures.",
      when: "Before go-live, alongside UAT, especially for enterprise systems.",
      how: "Verify runbooks, backups, recovery drills, monitoring/alerting and patching processes.",
      tip: "It's acceptance from operations' viewpoint — 'can we operate and support this?', not just 'does it work?'.",
      related: ["Recovery Testing", "Failover Testing", "Installation Testing"] },
    { t: "Contract Acceptance Testing", cat: "levels", d: "Confirming the software meets the criteria agreed in a contract before sign-off.",
      long: "Validates the delivered product against the specific, predefined acceptance criteria written into a contract.",
      when: "Vendor/outsourced deliveries where payment depends on meeting agreed terms.",
      how: "Run the contractually defined acceptance suite and document conformance.",
      tip: "The acceptance criteria are fixed up front in the contract — testing proves they're met.",
      related: ["Acceptance Testing (UAT)", "Regulatory Acceptance Testing", "Compliance / Conformance Testing"] },
    { t: "Regulatory Acceptance Testing", cat: "levels", d: "Confirming the software complies with legal/regulatory standards before release.",
      long: "Verifies the product meets the laws and regulations governing its domain (finance, healthcare, aviation) before it can legally ship.",
      when: "Regulated industries — e.g. HIPAA, PCI-DSS, GDPR, FDA.",
      how: "Test against the regulatory requirements and produce auditable evidence.",
      tip: "Failure here blocks release entirely — non-negotiable, with documentation for auditors.",
      related: ["Compliance / Conformance Testing", "Contract Acceptance Testing", "Security Testing"] },

    /* ── Functional Testing ── */
    { t: "Functional Testing", cat: "functional", d: "Verifying the system does what it should — every feature, input and business rule meets requirements.",
      long: "The umbrella for testing *what* the system does. Each function is verified against its specification using valid and invalid inputs.",
      when: "On every feature, at multiple levels (unit → system).",
      how: "Derive cases from requirements with black-box techniques; verify outputs and state.",
      tip: "Contrast with non-functional ('how well') — interviewers often ask for the distinction with examples.",
      related: ["Non-Functional Testing", "Smoke Testing", "Regression Testing"] },
    { t: "Smoke Testing", cat: "functional", d: "A wide, shallow check that a new build's critical paths work ('build verification'); if it fails, reject the build.",
      long: "A quick, broad pass over the most important functions to decide whether a build is stable enough to test further. Named after hardware 'power it on and see if it smokes'.",
      when: "Immediately on every new build, before deeper testing.",
      how: "Run a small suite covering core flows (login, key transactions); often automated as a CI gate.",
      tip: "Smoke = wide + shallow on a whole build. Sanity = narrow + deep on a specific change. Don't confuse them.",
      related: ["Sanity Testing", "Build (Build Verification)", "Regression Testing"] },
    { t: "Sanity Testing", cat: "functional", d: "A narrow, deep check of a specific fix or feature after a minor change, before deeper testing.",
      long: "A focused, usually unscripted check that a particular bug fix or new feature works and didn't obviously break its area — a subset of regression.",
      when: "After a small change or fix, to decide if fuller testing is worthwhile.",
      how: "Deeply exercise just the changed functionality and its immediate neighbours.",
      tip: "If sanity fails, reject the build before spending effort on full regression.",
      related: ["Smoke Testing", "Re-testing / Confirmation Testing", "Regression Testing"] },
    { t: "Regression Testing", cat: "functional", d: "Re-running existing tests to confirm new changes haven't broken previously working functionality.",
      long: "Guards against side effects: every change can break something elsewhere, so you re-run the relevant existing suite to confirm nothing regressed.",
      when: "After any code change — fixes, features, refactors, config, dependency bumps.",
      how: "Maintain an automated regression suite; use impact analysis and risk to scope which tests run.",
      tip: "Prime automation candidate — regression is repetitive and frequent, so its automation ROI is highest.",
      related: ["Re-testing / Confirmation Testing", "Automated Testing", "Impact Analysis"] },
    { t: "Re-testing / Confirmation Testing", cat: "functional", d: "Verifying that a specific reported defect has actually been fixed (distinct from regression).",
      long: "After a developer fixes a bug, you re-run the exact failing scenario on the new build to confirm it now passes.",
      when: "Whenever a defect is marked Fixed and returns to QA.",
      how: "Reproduce the original steps on the fixed build; if it passes, verify and close; if not, reopen.",
      tip: "Re-testing targets the *same* defect; regression checks *everything around* the change. Common interview trap.",
      related: ["Regression Testing", "Sanity Testing", "Maintenance Testing"] },
    { t: "Interface Testing", cat: "functional", d: "Verifying communication and data exchange between two components or systems through their interface.",
      long: "Checks that interfaces (APIs, message queues, UIs between modules) pass data correctly, handle errors, and respect contracts.",
      when: "Wherever two systems/modules communicate.",
      how: "Validate request/response formats, error handling, timeouts and data integrity across the boundary.",
      tip: "Closely tied to API and contract testing — the interface is where integration bugs hide.",
      related: ["API Testing", "System Integration Testing", "Contract Testing"] },
    { t: "API Testing", cat: "functional", d: "Testing application programming interfaces directly — status codes, schema, auth, errors — below the UI.",
      long: "Exercises endpoints without the UI: validates status codes, response schema, data correctness, auth/authz, error contracts, idempotency and edge cases. Fast and stable.",
      when: "The bulk of integration-level testing, especially in service/microservice architectures.",
      how: "Use tools (Postman, REST Assured, Playwright APIRequest); assert codes, body, headers; handle tokens.",
      tip: "Push verification to the API layer — it's faster and less brittle than UI tests for the same logic.",
      related: ["Interface Testing", "Contract Testing", "Backend Testing"] },
    { t: "Database Testing", cat: "functional", d: "Validating data integrity, CRUD operations, schema, stored procedures, triggers and constraints.",
      long: "Verifies the data layer directly: that operations persist correctly, constraints hold, transactions are ACID-safe, and the data matches what the UI/API reports.",
      when: "Data-centric apps, reporting/analytics, and any UI-to-DB verification.",
      how: "Run SQL to check counts, aggregates, duplicates, nulls, referential integrity and source-to-target reconciliation.",
      tip: "Beware join fan-out inflating SUMs; use anti-joins to find orphan/missing rows.",
      related: ["Backend Testing", "ETL / Data Pipeline Testing", "Analytics / Reporting UI Testing"] },
    { t: "GUI / UI Testing", cat: "functional", d: "Verifying graphical interface elements — layout, fonts, alignment, controls — appear and behave correctly.",
      long: "Checks the presentation layer: that elements render correctly, controls work, navigation flows, and the UI matches the design across states.",
      when: "Any user-facing application, especially after UI changes.",
      how: "Manual visual checks plus automated UI tests; visual-regression tools catch pixel-level drift.",
      tip: "Separate *functional* UI behaviour (automatable) from *aesthetic* judgement (human) — automate the former.",
      related: ["Visual Regression Testing", "Usability Testing", "Cross-Browser Testing"] },
    { t: "Backend Testing", cat: "functional", d: "Testing the server side: databases, APIs and business logic beneath the UI.",
      long: "Validates everything below the presentation layer — services, business rules, data stores — independently of the front end.",
      when: "When logic and data integrity matter more than presentation, or to isolate back-end defects.",
      how: "Test APIs and databases directly; verify business rules and data persistence.",
      tip: "Most senior testing lives here — it's faster, more stable and more powerful than UI testing.",
      related: ["API Testing", "Database Testing", "ETL / Data Pipeline Testing"] },
    { t: "Boundary Value Testing", cat: "functional", d: "Testing at the edges of input ranges (min, min±1, max, max±1) where off-by-one defects cluster.",
      long: "A design technique exploiting the fact that defects concentrate at boundaries; you test the edges of each equivalence partition rather than the middle.",
      when: "Any input with a range or limit — ages, lengths, quantities, dates.",
      how: "For a valid range a–b, test a-1, a, a+1, b-1, b, b+1.",
      tip: "Pairs with equivalence partitioning: partition to cut cases, then BVA the edges to catch off-by-ones.",
      related: ["Positive Testing", "Negative Testing", "Pairwise / Combinatorial Testing"] },
    { t: "Use Case Testing", cat: "functional", d: "Deriving tests from use cases — the end-to-end transactions a user performs with the system.",
      long: "Builds tests around complete user-system interactions (main flow + alternate/exception flows), ensuring real workflows are covered.",
      when: "Validating that business transactions work end-to-end from the user's perspective.",
      how: "For each use case, test the main success scenario plus every alternate and exception path.",
      tip: "Great for system/acceptance level — it maps directly to how users actually work.",
      related: ["End-to-End Testing", "Acceptance Testing (UAT)", "Functional Testing"] },
    { t: "Globalization Testing", cat: "functional", d: "Ensuring software works correctly across all target regions, languages and cultural settings worldwide.",
      long: "Confirms the product behaves correctly for a global audience — multiple languages, locales, currencies, time zones and cultural conventions.",
      when: "Products shipping to multiple countries/locales.",
      how: "Test with varied locale settings, character sets, and regional formats end to end.",
      tip: "Globalization is the umbrella; i18n (build for locales) and l10n (adapt to one locale) are its two halves.",
      related: ["Internationalization Testing (i18n)", "Localization Testing (l10n)", "Compatibility Testing"] },
    { t: "Internationalization Testing (i18n)", cat: "functional", d: "Verifying the product is built to support multiple locales without code changes (unicode, RTL layout).",
      long: "Checks the *engineering* readiness for localization: unicode support, externalized strings, layout that handles text expansion and right-to-left scripts, locale-aware formatting.",
      when: "Before localizing — confirm the app *can* be localized cleanly.",
      how: "Test with pseudo-localization, long strings, RTL locales, and non-Latin character sets.",
      tip: "i18n is about *capability* (can it adapt?); l10n is about a *specific* adaptation.",
      related: ["Localization Testing (l10n)", "Globalization Testing", "Localization (Language) Testing"] },
    { t: "Localization Testing (l10n)", cat: "functional", d: "Verifying correct adaptation to a specific locale — language, currency, date formats, cultural norms.",
      long: "Confirms a particular locale build is correct: translations accurate and untruncated, formats right, culturally appropriate, no hard-coded English.",
      when: "After translating/adapting for each target market.",
      how: "Native-language review plus checks of formats, layout, encoding and locale-specific behaviour.",
      tip: "Watch text expansion (German ~30% longer) breaking layouts and truncating labels.",
      related: ["Internationalization Testing (i18n)", "Globalization Testing", "Localization (Language) Testing"] },
    { t: "ETL / Data Pipeline Testing", cat: "functional", d: "Validating Extract-Transform-Load: completeness, transformation rules, integrity and source-to-target reconciliation.",
      long: "Proves data moves correctly from sources through transformations into a warehouse/target that BI reads — counts match, rules applied right, no duplicates, integrity preserved.",
      when: "Data warehousing, analytics and reporting pipelines.",
      how: "Test against the source-to-target mapping (STM): count reconciliation, transformation checks, dup/null checks, anti-joins, incremental/CDC loads.",
      tip: "Re-running a job must be idempotent — duplicate rows on re-run is a classic ETL defect.",
      related: ["Database Testing", "Analytics / Reporting UI Testing", "Big Data Testing"] },

    /* ── Non-Functional Testing ── */
    { t: "Non-Functional Testing", cat: "nonfunc", d: "Verifying quality attributes — how well the system performs — rather than what it does.",
      long: "Covers the 'how well' attributes: performance, security, usability, reliability, compatibility and more. Often measured against SLAs rather than pass/fail rules.",
      when: "Alongside functional testing, especially before release of production systems.",
      how: "Define measurable targets (response time, uptime, WCAG level) and test against them.",
      tip: "Functional asks 'does it work?'; non-functional asks 'is it fast, secure, usable and reliable enough?'.",
      related: ["Functional Testing", "Performance Testing", "Security Testing"] },
    { t: "Usability Testing", cat: "nonfunc", d: "Evaluating how easy, intuitive and satisfying the product is for real users to use.",
      long: "Observes real users attempting tasks to find friction, confusion and inefficiency in the experience — a human-judgement activity.",
      when: "During design and before release of user-facing features.",
      how: "Give representative users real tasks, observe (think-aloud), measure success/time/errors, gather feedback.",
      tip: "Can't be fully automated — it's about human perception; pair with accessibility testing.",
      related: ["Accessibility Testing", "GUI / UI Testing", "Manual Testing"] },
    { t: "Accessibility Testing", cat: "nonfunc", d: "Verifying the product is usable by people with disabilities, against standards like WCAG (screen readers, contrast, keyboard nav).",
      long: "Ensures people with visual, motor, auditory or cognitive disabilities can use the product — often a legal requirement (ADA, Section 508, EN 301 549).",
      when: "Any public-facing or regulated product.",
      how: "Test with screen readers, keyboard-only nav, contrast checkers and automated scanners (axe), against WCAG A/AA.",
      tip: "Automated tools catch ~30–50% of issues — manual testing with assistive tech is essential.",
      related: ["Usability Testing", "Compliance / Conformance Testing", "GUI / UI Testing"] },
    { t: "Compatibility Testing", cat: "nonfunc", d: "Checking the software works across different browsers, devices, OSes and configurations.",
      long: "Confirms consistent behaviour and appearance across the matrix of environments your users have.",
      when: "Web and cross-platform apps with diverse user environments.",
      how: "Test across a prioritized matrix of browser/OS/device combos, often via a device cloud.",
      tip: "Use analytics to prioritize the matrix — test the environments your users actually use most.",
      related: ["Cross-Browser Testing", "Cross-Platform Testing", "Responsive / Cross-Device Testing"] },
    { t: "Cross-Browser Testing", cat: "nonfunc", d: "Compatibility testing focused on consistent behaviour across web browsers (Chrome, Firefox, Safari, Edge).",
      long: "Verifies a web app renders and behaves consistently across browsers and their versions, which differ in rendering engines and feature support.",
      when: "Any web application with a broad audience.",
      how: "Run the suite across browsers, in parallel via a grid/device cloud (BrowserStack, Sauce Labs).",
      tip: "A subset of compatibility testing; automate it across a grid to keep it affordable.",
      related: ["Compatibility Testing", "Cross-Platform Testing", "Visual Regression Testing"] },
    { t: "Cross-Platform Testing", cat: "nonfunc", d: "Verifying consistent behaviour across operating systems (Windows, macOS, Linux, Android, iOS).",
      long: "Confirms the application works correctly across the operating systems it targets, which differ in file systems, fonts, APIs and conventions.",
      when: "Desktop, mobile and multi-OS products.",
      how: "Execute tests on each target OS; watch OS-specific behaviours and integrations.",
      tip: "Closely related to cross-browser and device testing — together they form compatibility coverage.",
      related: ["Compatibility Testing", "Cross-Browser Testing", "Mobile Application Testing"] },
    { t: "Reliability Testing", cat: "nonfunc", d: "Verifying the system performs failure-free for a specified period under stated conditions.",
      long: "Measures how dependably the system runs over time — failure rates, MTBF, and stability under sustained normal use.",
      when: "Systems where uptime and dependability are critical.",
      how: "Run extended operations under realistic load and track failures over time.",
      tip: "Overlaps soak testing; reliability emphasizes the failure-rate metric over the duration.",
      related: ["Soak / Endurance Testing", "Recovery Testing", "Failover Testing"] },
    { t: "Recovery Testing", cat: "nonfunc", d: "Verifying the system recovers gracefully from crashes, network loss and hardware failure.",
      long: "Deliberately forces failures to confirm the system restores data and service correctly and within acceptable time.",
      when: "Mission-critical systems and as part of operational acceptance.",
      how: "Kill processes, cut networks, pull power; verify restart, data integrity and recovery time.",
      tip: "Test the *recovery*, not just that it fails — RTO/RPO targets matter.",
      related: ["Failover Testing", "Reliability Testing", "Operational Acceptance Testing"] },
    { t: "Failover Testing", cat: "nonfunc", d: "Verifying the system switches to a backup/redundant system without data loss when a component fails.",
      long: "Confirms high-availability mechanisms work: when a node/service fails, traffic fails over to a standby seamlessly.",
      when: "HA architectures with redundancy and clustering.",
      how: "Simulate component failure and verify automatic failover, data consistency and no/minimal downtime.",
      tip: "Closely tied to recovery and chaos engineering — prove redundancy actually works before prod does the test for you.",
      related: ["Recovery Testing", "Chaos Engineering", "Reliability Testing"] },
    { t: "Installation Testing", cat: "nonfunc", d: "Verifying the software installs, upgrades and uninstalls correctly across environments.",
      long: "Validates the full install lifecycle: fresh install, upgrade (with data migration), repair and clean uninstall, across configurations.",
      when: "Desktop/mobile/server software that users or ops must deploy.",
      how: "Test install/upgrade/rollback/uninstall on each target environment; verify no leftover artifacts.",
      tip: "Upgrades with data migration are the riskiest path — test old→new with real-shaped data.",
      related: ["Configuration Testing", "Operational Acceptance Testing", "Compatibility Testing"] },
    { t: "Configuration Testing", cat: "nonfunc", d: "Verifying the system behaves correctly under different hardware/software configurations and settings.",
      long: "Checks the app across permutations of configurable options, hardware, drivers and settings to ensure correct behaviour.",
      when: "Highly configurable products or varied deployment targets.",
      how: "Test a prioritized set of configuration combinations (use pairwise to cut the matrix).",
      tip: "Configuration combos explode fast — pairwise testing makes coverage tractable.",
      related: ["Compatibility Testing", "Installation Testing", "Pairwise / Combinatorial Testing"] },
    { t: "Compliance / Conformance Testing", cat: "nonfunc", d: "Verifying the system adheres to standards, regulations or internal guidelines (e.g. GDPR, HIPAA, ISO).",
      long: "Confirms the product conforms to applicable external standards or internal policies, producing auditable evidence.",
      when: "Regulated domains and standards-bound products.",
      how: "Map requirements to the standard's controls and test each, documenting conformance.",
      tip: "Keep traceable evidence — auditors need proof each control was tested.",
      related: ["Regulatory Acceptance Testing", "Security Testing", "Accessibility Testing"] },
    { t: "Maintainability Testing", cat: "nonfunc", d: "Assessing how easily the software can be modified, corrected or enhanced.",
      long: "Evaluates qualities that make change cheap and safe: modularity, readability, low coupling, good test coverage and documentation.",
      when: "During code review and architecture assessment.",
      how: "Use static analysis (complexity, duplication), review structure, and measure change effort.",
      tip: "High cyclomatic complexity and low coverage are red flags for poor maintainability.",
      related: ["Static Testing", "Portability Testing", "Efficiency Testing"] },
    { t: "Portability Testing", cat: "nonfunc", d: "Assessing how easily the software can be moved to different environments or platforms.",
      long: "Measures the effort to move the software to new hardware, OS or environments — adaptability, installability and replaceability.",
      when: "Software expected to run across or migrate between environments.",
      how: "Deploy to different target environments and assess adaptation effort and correctness.",
      tip: "Containerization dramatically improves portability — a common modern answer.",
      related: ["Compatibility Testing", "Cross-Platform Testing", "Installation Testing"] },
    { t: "Efficiency Testing", cat: "nonfunc", d: "Measuring how well the system uses resources (CPU, memory, network) for the work it performs.",
      long: "Assesses resource consumption relative to throughput — are we using CPU, memory, disk and network economically?",
      when: "Cost-sensitive, high-scale or resource-constrained systems.",
      how: "Profile resource usage under load; compare against budgets and look for waste/leaks.",
      tip: "Tightly linked to performance — efficiency is performance per unit of resource (and cost).",
      related: ["Performance Testing", "Soak / Endurance Testing", "Scalability Testing"] },

    /* ── Performance Testing ── */
    { t: "Performance Testing", cat: "perf", d: "Evaluating speed, responsiveness and stability under a given workload (the parent category).",
      long: "Measures how the system behaves under load — response times, throughput and resource use — against defined SLAs, using percentiles not averages.",
      when: "Before releasing anything with meaningful traffic or SLAs.",
      how: "Model realistic load with tools (JMeter, k6, Gatling); observe with APM/tracing; report p95/p99.",
      tip: "Report percentiles — a 200ms average can hide a 4s p99 hurting thousands of users.",
      related: ["Load Testing", "Stress Testing", "Scalability Testing"] },
    { t: "Load Testing", cat: "perf", d: "Testing at expected concurrent load to verify response time and throughput meet SLAs.",
      long: "Applies the anticipated production load to confirm the system meets its performance targets under normal and peak expected conditions.",
      when: "Validating capacity for expected traffic before launch or a big event.",
      how: "Ramp virtual users to target levels; measure latency, throughput and error rate against SLAs.",
      tip: "Load = expected demand. Stress = beyond capacity. Spike = sudden surge. Know the trio cold.",
      related: ["Stress Testing", "Spike Testing", "Performance Testing"] },
    { t: "Stress Testing", cat: "perf", d: "Pushing beyond capacity to find the breaking point and observe the failure mode (graceful vs crash).",
      long: "Deliberately overloads the system past its limits to learn where and how it breaks, and whether it degrades gracefully and recovers.",
      when: "Understanding limits, capacity planning, and resilience validation.",
      how: "Increase load beyond expected peak until failure; observe behaviour and recovery.",
      tip: "The goal isn't to pass — it's to learn the failure mode and confirm graceful degradation.",
      related: ["Load Testing", "Spike Testing", "Soak / Endurance Testing"] },
    { t: "Spike Testing", cat: "perf", d: "Applying a sudden sharp surge in load to test autoscaling and recovery (e.g. a flash sale).",
      long: "Tests how the system copes with an abrupt, large jump in load and how quickly it recovers when the spike subsides.",
      when: "Systems facing bursty traffic — sales, ticket drops, viral events.",
      how: "Instantly jump virtual users far above baseline, hold, then drop; observe scaling and stability.",
      tip: "Validates autoscaling lag — does capacity arrive before users see errors?",
      related: ["Load Testing", "Stress Testing", "Scalability Testing"] },
    { t: "Soak / Endurance Testing", cat: "perf", d: "Sustained load over hours/days to expose memory leaks and resource exhaustion.",
      long: "Holds a moderate load for a long duration to surface slow-building problems: memory leaks, connection-pool exhaustion, log/disk fill, degradation over time.",
      when: "Before releasing long-running services that must stay up for days/weeks.",
      how: "Run steady load for an extended period; watch memory, handles, connections and response trend.",
      tip: "The go-to for finding leaks — they only appear over time, invisible to short load tests.",
      related: ["Load Testing", "Reliability Testing", "Efficiency Testing"] },
    { t: "Volume Testing", cat: "perf", d: "Testing with large volumes of data to evaluate database and query performance.",
      long: "Loads the system with large *amounts of data* (big tables, large files) to assess how data volume affects performance and stability.",
      when: "Data-heavy systems, reporting and analytics with growing datasets.",
      how: "Populate production-scale data; measure query times, indexing and throughput.",
      tip: "Distinct from load testing (which is about concurrent users) — volume is about data size.",
      related: ["Performance Testing", "Big Data Testing", "Database Testing"] },
    { t: "Scalability Testing", cat: "perf", d: "Verifying capacity grows appropriately (ideally linearly) as resources are added.",
      long: "Measures how well the system scales — vertically (bigger machines) and horizontally (more instances) — and finds scaling limits.",
      when: "Planning for growth and validating elasticity/architecture.",
      how: "Increase load and resources together; chart capacity vs resources to find linearity and ceilings.",
      tip: "Look for the point where adding resources stops adding capacity — that's your architectural bottleneck.",
      related: ["Load Testing", "Spike Testing", "Performance Testing"] },
    { t: "Concurrency Testing", cat: "perf", d: "Testing simultaneous access by many users/threads to expose race conditions, deadlocks and lost updates.",
      long: "Focuses on what happens when multiple actors hit the same data/resource at once — races, deadlocks, lost updates and isolation issues.",
      when: "Shared-resource systems, financial transactions, booking/inventory.",
      how: "Drive parallel operations on the same records; verify correctness under interleaving.",
      tip: "Test ACID isolation by concurrent updates to one record — a great way to expose lost-update bugs.",
      related: ["Load Testing", "Database Testing", "Stress Testing"] },

    /* ── Security Testing ── */
    { t: "Security Testing", cat: "security", d: "Verifying the system protects data and resists attack — confidentiality, integrity, availability.",
      long: "Assesses how well the system defends against threats — authentication, authorization, input handling, encryption — typically guided by the OWASP Top 10.",
      when: "Continuously for any system handling sensitive data or exposed to the internet.",
      how: "Combine manual testing (authz, injection, XSS), automated SAST/DAST, and dependency scanning.",
      tip: "QA's highest-value check: authorization — can user A access user B's data (IDOR)?",
      related: ["Penetration Testing", "Vulnerability Scanning", "DAST"] },
    { t: "Vulnerability Scanning", cat: "security", d: "Automated scanning for known weaknesses (outdated libs, misconfigurations, open ports).",
      long: "Tools scan the application and infrastructure against databases of known vulnerabilities, flagging issues to triage and fix.",
      when: "Regularly in CI/CD and on infrastructure.",
      how: "Run scanners (OWASP ZAP, Nessus, dependency scanners) and triage findings by severity.",
      tip: "Automated and broad but shallow — it finds *known* issues; pen testing finds novel exploit chains.",
      related: ["Penetration Testing", "SAST", "DAST"] },
    { t: "Penetration Testing", cat: "security", d: "Authorised simulated attacks that find and exploit vulnerabilities before real attackers do.",
      long: "Skilled testers actively attempt to breach the system — chaining vulnerabilities, escalating privileges — to demonstrate real-world risk.",
      when: "Periodically and before major releases of sensitive systems.",
      how: "Reconnaissance → scanning → exploitation → post-exploitation → reporting, under explicit authorization.",
      tip: "Always requires written authorization and scope — unauthorized testing is illegal.",
      related: ["Ethical Hacking", "Vulnerability Scanning", "Security Testing"] },
    { t: "Ethical Hacking", cat: "security", d: "Authorised offensive security probing of a system to discover exploitable weaknesses.",
      long: "Broad authorized offensive security work to find weaknesses; penetration testing is a focused, scoped subset of it.",
      when: "Proactive security assessment with permission.",
      how: "Apply attacker techniques across the system within agreed rules of engagement.",
      tip: "Ethical = authorized + scoped + reported responsibly. That word does a lot of legal work.",
      related: ["Penetration Testing", "Vulnerability Scanning", "Security Testing"] },
    { t: "SAST", cat: "security", d: "Static Application Security Testing — analysing source code for vulnerabilities without running it.",
      long: "Inspects source/bytecode for insecure patterns (injection, hard-coded secrets, unsafe APIs) early, before execution.",
      when: "In the IDE and CI, on every change — true shift-left security.",
      how: "Integrate SAST tools (SonarQube, Semgrep, Checkmarx) into the pipeline; triage findings.",
      tip: "Finds issues early and cheaply but can be noisy (false positives); DAST complements it at runtime.",
      related: ["DAST", "Static Testing", "Vulnerability Scanning"] },
    { t: "DAST", cat: "security", d: "Dynamic Application Security Testing — probing the running application for vulnerabilities.",
      long: "Attacks the running app from the outside (no source needed), finding runtime issues like injection, XSS and misconfigurations.",
      when: "Against deployed builds in staging/CI.",
      how: "Run DAST tools (OWASP ZAP, Burp) to crawl and attack the live application.",
      tip: "DAST sees what SAST can't (runtime/config) and vice versa — use both.",
      related: ["SAST", "Penetration Testing", "Security Testing"] },
    { t: "Risk Assessment / Security Audit", cat: "security", d: "Systematic review of security controls, policies and configuration against a standard.",
      long: "A structured evaluation of the security posture — controls, processes, configurations — against a framework, producing prioritized risk findings.",
      when: "Periodically, for compliance and governance.",
      how: "Review against a standard (ISO 27001, NIST), interview teams, inspect configs, rate risks.",
      tip: "More about process and governance than exploitation — complements hands-on pen testing.",
      related: ["Compliance / Conformance Testing", "Penetration Testing", "Security Testing"] },

    /* ── Maintenance & Change ── */
    { t: "Maintenance Testing", cat: "change", d: "Testing changes to a system already in production — fixes, enhancements, migrations, retirements.",
      long: "Covers testing triggered by changes to a live system: corrective fixes, adaptive changes (new OS/platform), enhancements, data migrations and decommissioning.",
      when: "After release, throughout the system's operational life.",
      how: "Use impact analysis to scope what changed and what to regression test.",
      tip: "Impact analysis is the key skill — test the change *and* its blast radius, not everything blindly.",
      related: ["Regression Testing", "Impact Analysis", "Re-testing / Confirmation Testing"] },
    { t: "Confirmation Testing", cat: "change", d: "Re-running the failing test after a fix to confirm the original defect is resolved.",
      long: "Another name for re-testing: execute the exact scenario that revealed a defect on the fixed build to confirm it's gone.",
      when: "Whenever a fix is delivered for verification.",
      how: "Reproduce the original failing steps; pass → verify/close, fail → reopen.",
      tip: "Confirmation = the same bug now fixed; regression = nothing else broke as a result.",
      related: ["Re-testing / Confirmation Testing", "Regression Testing", "Maintenance Testing"] },
    { t: "Impact Analysis", cat: "change", d: "Determining what areas a change affects, to scope the regression set efficiently.",
      long: "Analyses a change to identify which features/modules could be affected, so regression targets the right areas instead of everything.",
      when: "Before regression testing any change.",
      how: "Trace dependencies (code, data, requirements via RTM, git history/churn) to map the blast radius.",
      tip: "Risk-based impact analysis is how seniors cut regression time without raising escaped defects.",
      related: ["Regression Testing", "Risk-Based Testing", "Maintenance Testing"] },
    { t: "Build (Build Verification)", cat: "change", d: "An automated smoke suite run on each build to confirm it's stable enough for further testing.",
      long: "Build Verification Test (BVT) is an automated smoke pass that gates each new build — if core flows fail, the build is rejected before deeper testing.",
      when: "On every build in CI, before deeper test stages.",
      how: "Run a fast, automated suite over critical paths as a pipeline gate.",
      tip: "Keep it fast and reliable — a flaky BVT erodes trust in the whole pipeline.",
      related: ["Smoke Testing", "Continuous Testing", "Regression Testing"] },

    /* ── Development-Driven ── */
    { t: "Test-Driven Development (TDD)", cat: "dev", d: "Write a failing test first, then minimal code to pass it, then refactor (red-green-refactor).",
      long: "A development discipline where tests drive design: write a tiny failing test, make it pass with minimal code, refactor, repeat. Produces high coverage and testable design.",
      when: "Unit-level development, especially for complex logic.",
      how: "Red (write failing test) → Green (pass it) → Refactor (clean up) in tight loops.",
      tip: "TDD is a *design* practice as much as a testing one — it forces small, testable units.",
      related: ["Unit Testing", "Behavior-Driven Development (BDD)", "Acceptance Test-Driven Development (ATDD)"] },
    { t: "Behavior-Driven Development (BDD)", cat: "dev", d: "Executable specs in plain language (Gherkin Given/When/Then) shared by business, dev and QA.",
      long: "Extends TDD to collaborative, business-readable specifications. Scenarios in Given/When/Then become living documentation and automated acceptance tests.",
      when: "When shared understanding across business, dev and QA matters.",
      how: "Write Gherkin scenarios; automate steps with Cucumber/SpecFlow/Behave; keep them executable.",
      tip: "BDD's real value is the *conversation* and shared language, not just the tooling.",
      related: ["Acceptance Test-Driven Development (ATDD)", "Test-Driven Development (TDD)", "Specification by Example"] },
    { t: "Acceptance Test-Driven Development (ATDD)", cat: "dev", d: "The team defines acceptance tests collaboratively before development, driving the implementation.",
      long: "Business, dev and QA agree concrete acceptance tests *before* coding; those tests define 'done' and guide development.",
      when: "Story kickoff in agile teams (the Three Amigos).",
      how: "Collaboratively write acceptance criteria as tests up front; build until they pass.",
      tip: "ATDD focuses on *acceptance* criteria; TDD on *unit* design — they complement each other.",
      related: ["Behavior-Driven Development (BDD)", "Test-Driven Development (TDD)", "Acceptance Testing (UAT)"] },
    { t: "Specification by Example", cat: "dev", d: "Deriving requirements and tests from concrete examples agreed with stakeholders.",
      long: "Uses real, concrete examples of desired behaviour to clarify requirements and become automated, executable specifications.",
      when: "Refinement of ambiguous requirements.",
      how: "Collaboratively capture key examples; turn them into living, automated specs.",
      tip: "Concrete examples kill ambiguity faster than prose requirements ever can.",
      related: ["Behavior-Driven Development (BDD)", "Acceptance Test-Driven Development (ATDD)", "Use Case Testing"] },
    { t: "Unit-Test-First / Component Tests", cat: "dev", d: "Developer-authored automated checks at the base of the pyramid, run on every change in CI.",
      long: "The practice of writing fast, isolated developer tests as the foundation of the suite — the wide base of the pyramid that catches most defects cheapest.",
      when: "Continuously during development.",
      how: "Write unit/component tests alongside code; run them on every commit.",
      tip: "A strong unit base is what makes the whole pyramid (and CI speed) work.",
      related: ["Unit Testing", "Component Testing", "Continuous Testing"] },

    /* ── Specialized & Modern ── */
    { t: "A/B Testing", cat: "specialized", d: "Comparing two variants with real users to measure which performs better on a metric.",
      long: "A controlled experiment splitting live traffic between variants (A and B) to measure which drives a target metric better — a product/analytics technique QA helps validate.",
      when: "Optimizing UX, conversion or features with real users.",
      how: "Randomly assign users to variants, measure the metric, test for statistical significance.",
      tip: "QA's role: verify correct bucketing, no cross-contamination, and accurate metric tracking.",
      related: ["Canary Testing", "Testing in Production (Shift-Right)", "Usability Testing"] },
    { t: "Canary Testing", cat: "specialized", d: "Releasing a change to a small subset of users first, monitoring, then expanding if healthy.",
      long: "A gradual rollout: a small 'canary' group gets the new version while you watch metrics; if healthy you ramp up, otherwise roll back fast.",
      when: "De-risking production releases of impactful changes.",
      how: "Route a small % of traffic to the new version; monitor errors/latency; expand or roll back.",
      tip: "A shift-right safety net — catches real-world issues with limited blast radius.",
      related: ["Testing in Production (Shift-Right)", "Beta Testing", "A/B Testing"] },
    { t: "Chaos Engineering", cat: "specialized", d: "Deliberately injecting failures in production-like environments to test resilience.",
      long: "Proactively experiments on a system (killing nodes, adding latency, dropping dependencies) to build confidence it withstands turbulent real-world conditions.",
      when: "Distributed/microservice systems where resilience is critical.",
      how: "Form a hypothesis, inject controlled failure (e.g. Chaos Monkey), observe, and harden weaknesses.",
      tip: "Start small and in staging; the goal is to find weaknesses before they find you.",
      related: ["Failover Testing", "Recovery Testing", "Reliability Testing"] },
    { t: "Mutation Testing", cat: "specialized", d: "Introducing small code mutations to check whether the test suite detects them — measures test quality.",
      long: "Automatically makes tiny changes (mutants) to the code; if tests still pass, they failed to 'kill' the mutant, revealing weak assertions. Measures test *effectiveness*, not just coverage.",
      when: "Hardening critical test suites where coverage looks high but quality is uncertain.",
      how: "Run a mutation tool (PIT, Stryker); aim to maximize the mutation-kill score.",
      tip: "Answers the question coverage can't: 'do my tests actually *assert* the right things?'.",
      related: ["White-Box Testing", "Unit Testing", "Test-Driven Development (TDD)"] },
    { t: "Fuzz Testing (Fuzzing)", cat: "specialized", d: "Feeding large amounts of malformed/random data to find crashes, leaks and security holes.",
      long: "Automatically bombards inputs with malformed, unexpected or random data to trigger crashes, memory errors and security vulnerabilities.",
      when: "Parsers, file/protocol handlers, and security-sensitive input surfaces.",
      how: "Use a fuzzer (AFL, libFuzzer) to generate inputs and monitor for crashes/leaks.",
      tip: "Excellent at finding security and robustness bugs humans would never think to type.",
      related: ["Negative Testing", "Security Testing", "Monkey Testing"] },
    { t: "Property-Based Testing", cat: "specialized", d: "Asserting that properties hold across many auto-generated inputs, rather than fixed examples.",
      long: "Instead of example-based cases, you state invariants (properties) and a tool generates many inputs to try to falsify them, shrinking failures to a minimal case.",
      when: "Logic with clear invariants — serialization round-trips, sorting, parsers.",
      how: "Use a framework (QuickCheck, Hypothesis, fast-check); define properties and generators.",
      tip: "Finds edge cases example tests miss; the auto-shrinking gives you a minimal repro for free.",
      related: ["Fuzz Testing (Fuzzing)", "Unit Testing", "Model-Based Testing"] },
    { t: "Contract Testing", cat: "specialized", d: "Verifying a consumer and provider agree on the API interface independently (e.g. Pact), avoiding full E2E.",
      long: "The consumer defines expectations of a provider as a contract; the provider verifies it can meet them — catching breaking API changes without deploying both together.",
      when: "Microservice architectures with independently deployed services.",
      how: "Consumer publishes a contract (Pact); provider runs it in CI to verify compatibility.",
      tip: "Gives integration confidence at unit-test speed — reserve a few E2E tests for critical journeys.",
      related: ["API Testing", "Integration Testing", "System Integration Testing"] },
    { t: "Visual Regression Testing", cat: "specialized", d: "Comparing screenshots against a baseline to catch unintended visual/UI changes.",
      long: "Captures rendered screenshots and diffs them against approved baselines to detect pixel-level UI regressions automated functional tests would miss.",
      when: "UI-heavy apps and design systems where appearance matters.",
      how: "Use tools (Percy, Applitools, Playwright snapshots); review and approve intentional changes.",
      tip: "Tame flakiness with consistent rendering (fonts, animations off) and tolerance thresholds.",
      related: ["Snapshot Testing", "GUI / UI Testing", "Cross-Browser Testing"] },
    { t: "Snapshot Testing", cat: "specialized", d: "Saving a rendered output and asserting future runs match the stored snapshot.",
      long: "Serializes a component's output (e.g. rendered DOM/JSON) into a stored snapshot; tests fail if output changes, prompting review.",
      when: "Component/UI libraries and serialized output where unexpected change is a regression.",
      how: "Generate snapshots (Jest), commit them, review diffs and update intentionally.",
      tip: "Beware 'snapshot rot' — blindly updating snapshots defeats the purpose.",
      related: ["Visual Regression Testing", "Unit Testing", "Component Testing"] },
    { t: "Model-Based Testing", cat: "specialized", d: "Generating test cases automatically from a model of the system's expected behaviour.",
      long: "Builds a formal model (e.g. a state machine) of expected behaviour, then auto-generates and runs tests that traverse it — great coverage of states and transitions.",
      when: "Systems with complex state logic and many transitions.",
      how: "Model states/transitions; use an MBT tool to generate paths and execute them.",
      tip: "Strong for state-heavy systems; the model itself becomes valuable living documentation.",
      related: ["Use Case Testing", "Property-Based Testing", "Automated Testing"] },
    { t: "Risk-Based Testing", cat: "specialized", d: "Prioritising test effort by risk (probability × impact) so high-risk areas get the deepest testing.",
      long: "Allocates testing depth by risk score rather than uniformly — high-probability, high-impact areas get exhaustive testing; low-risk areas get a light pass.",
      when: "Always, but especially under time pressure when you can't test everything.",
      how: "Score features on likelihood × impact (using defect history, churn, business value) and test accordingly.",
      tip: "The senior mindset for the 'release is tomorrow and regression isn't done' question.",
      related: ["Impact Analysis", "Exploratory Testing", "Pairwise / Combinatorial Testing"] },
    { t: "Data-Driven Testing", cat: "specialized", d: "Running the same test logic against multiple data sets stored externally (CSV, Excel, JSON).",
      long: "Separates test data from test logic so one parameterized test runs across many input/expected-output rows — efficient coverage of combinations.",
      when: "Validating the same flow across many input variations (e.g. login matrix).",
      how: "Externalize data; parameterize the test to iterate over each row.",
      tip: "Keeps suites DRY — add a data row, not a new test, to cover another case.",
      related: ["Keyword-Driven Testing", "Automated Testing", "Pairwise / Combinatorial Testing"] },
    { t: "Keyword-Driven Testing", cat: "specialized", d: "Building tests from reusable keywords/actions, separating test logic from test design.",
      long: "Tests are expressed as sequences of high-level keywords (e.g. Login, AddToCart) implemented once in code — letting non-coders author tests.",
      when: "Teams wanting business-readable, maintainable automation authored by non-developers.",
      how: "Build a keyword library; compose test cases from keywords (e.g. Robot Framework).",
      tip: "Maintainable and accessible, but the keyword framework itself needs careful design.",
      related: ["Data-Driven Testing", "Behavior-Driven Development (BDD)", "Automated Testing"] },
    { t: "Pairwise / Combinatorial Testing", cat: "specialized", d: "Covering all pairs of input values to slash combinations while keeping high defect-detection.",
      long: "Based on the finding that most defects come from interactions of just two factors, it covers all *pairs* of values — turning thousands of combinations into a few dozen tests.",
      when: "Many parameters with many values (configurations, forms) where full combinations explode.",
      how: "Use an all-pairs tool (PICT, Hexawise) to generate the minimal covering set.",
      tip: "5 fields × 4 options = 1024 combos → ~20 pairwise tests with most of the defect-finding power.",
      related: ["Boundary Value Testing", "Configuration Testing", "Data-Driven Testing"] },
    { t: "Continuous Testing", cat: "specialized", d: "Running automated tests continuously throughout the CI/CD pipeline for fast quality feedback.",
      long: "Embeds automated tests at every pipeline stage (commit → build → deploy) as quality gates, giving immediate feedback and enabling safe, frequent releases.",
      when: "Any CI/CD pipeline aiming for fast, reliable delivery.",
      how: "Stage tests fast-to-slow (unit → API → E2E) with quality gates that block promotion.",
      tip: "Keep the PR gate under ~10 minutes; run heavy regression nightly to preserve developer flow.",
      related: ["Automated Testing", "Build (Build Verification)", "Regression Testing"] },
    { t: "Testing in Production (Shift-Right)", cat: "specialized", d: "Validating in the live environment via canary, feature flags, observability and synthetic monitoring.",
      long: "Acknowledges you can't replicate production perfectly, so you test safely *in* it — feature flags, canaries, observability and monitoring — to learn from real usage.",
      when: "Complementing pre-prod testing for complex, high-scale systems.",
      how: "Use flags/canaries to limit blast radius; watch metrics, logs and traces; roll back fast.",
      tip: "Shift-right complements shift-left — catch early *and* learn from production.",
      related: ["Canary Testing", "Synthetic Monitoring", "A/B Testing"] },
    { t: "Synthetic Monitoring", cat: "specialized", d: "Running scripted transactions against production continuously to detect issues before users do.",
      long: "Bots execute key user journeys against production on a schedule, alerting on failures or slowdowns — catching outages before real users complain.",
      when: "Production monitoring of critical flows (login, checkout) 24/7.",
      how: "Script journeys; run from multiple locations on a cadence; alert on failures/SLA breaches.",
      tip: "A form of testing in production — your always-on smoke test against the live system.",
      related: ["Testing in Production (Shift-Right)", "Smoke Testing", "Continuous Testing"] },
    { t: "Agile Testing", cat: "specialized", d: "Testing embedded within iterative development — in-sprint, whole-team-owned, continuous.",
      long: "Testing woven through every sprint and ceremony rather than a downstream phase — QA clarifies stories, tests in-sprint, and the whole team owns quality.",
      when: "Scrum/Kanban teams delivering in iterations.",
      how: "Engage in refinement/planning, test stories as built, automate alongside, raise quality in retros.",
      tip: "Frame quality as a *team property* — you remove the gate, you're not the gate.",
      related: ["Continuous Testing", "Pair Testing", "Behavior-Driven Development (BDD)"] },

    /* ── Domain / Platform-Specific ── */
    { t: "Mobile Application Testing", cat: "domain", d: "Testing mobile apps across devices, OS versions, networks, gestures, interruptions and battery/perf.",
      long: "Covers the unique mobile concerns: device/OS fragmentation, gestures, interruptions (calls, notifications), network changes, battery, permissions and app-store guidelines.",
      when: "Native and hybrid mobile apps.",
      how: "Test on real devices and emulators (often a device cloud); cover interruptions, networks and OS versions.",
      tip: "Real-device testing matters — emulators miss sensors, performance and real network behaviour.",
      related: ["Responsive / Cross-Device Testing", "Cross-Platform Testing", "Compatibility Testing"] },
    { t: "Responsive / Cross-Device Testing", cat: "domain", d: "Verifying layout and behaviour adapt correctly across screen sizes and devices.",
      long: "Confirms a responsive UI reflows and remains usable from small phones to large desktops — no overlap, truncation or broken touch targets.",
      when: "Any responsive web or adaptive app.",
      how: "Test across breakpoints and real devices; check orientation, touch targets and reflow.",
      tip: "Test at the breakpoints *and* just on either side of them — that's where layouts break.",
      related: ["Mobile Application Testing", "Cross-Browser Testing", "GUI / UI Testing"] },
    { t: "Cloud Testing", cat: "domain", d: "Testing applications and infrastructure hosted in the cloud — scalability, multi-tenancy, services.",
      long: "Validates cloud-hosted systems: elasticity, multi-tenancy isolation, managed-service integration, resilience and cost-efficiency, often using cloud-based test infrastructure.",
      when: "Cloud-native and SaaS products.",
      how: "Test autoscaling, failover, tenant isolation and service integrations under realistic conditions.",
      tip: "Multi-tenancy isolation is a key check — one tenant must never see another's data.",
      related: ["Scalability Testing", "Failover Testing", "Performance Testing"] },
    { t: "Big Data Testing", cat: "domain", d: "Validating processing, quality and performance of very large datasets across distributed systems.",
      long: "Tests big-data pipelines (Hadoop/Spark/streaming) for data quality, transformation correctness and performance at massive scale across distributed nodes.",
      when: "Data platforms processing high-volume/velocity/variety data.",
      how: "Validate ingestion, transformation logic, completeness and performance across the cluster.",
      tip: "Three V's — Volume, Velocity, Variety — frame what makes big-data testing distinct.",
      related: ["ETL / Data Pipeline Testing", "Volume Testing", "Database Testing"] },
    { t: "Analytics / Reporting UI Testing", cat: "domain", d: "Validating dashboards: sorting, filtering, charts, drilldowns and UI-to-database data accuracy.",
      long: "Tests BI/reporting interfaces where each control (sort, filter, chart, drilldown) must stay faithful to the underlying data, reconciled against SQL.",
      when: "Dashboards, BI tools and analytics products.",
      how: "Verify UI value == table value == SQL result; check drilldown reconciliation, pagination totals and exports.",
      tip: "Numeric columns sorting as 1,10,2,3 (string order) is the classic reporting-UI defect.",
      related: ["Database Testing", "ETL / Data Pipeline Testing", "GUI / UI Testing"] },
    { t: "Game Testing", cat: "domain", d: "Testing video games — functionality, performance, graphics, multiplayer, balance and exploits.",
      long: "Covers gameplay logic, physics, graphics/audio, performance (frame rate), multiplayer sync, save/load, balance and exploit hunting — plus heavy exploratory and compatibility testing.",
      when: "Game development across platforms.",
      how: "Combine scripted, exploratory and soak testing; verify across hardware and network conditions.",
      tip: "Exploratory and 'break the rules' testing shine here — players will try everything.",
      related: ["Exploratory Testing", "Performance Testing", "Compatibility Testing"] },
    { t: "IoT / Embedded Testing", cat: "domain", d: "Testing connected devices and firmware — hardware-software integration, connectivity, power, sensors.",
      long: "Validates embedded/IoT systems where software meets hardware: sensor accuracy, connectivity, power management, firmware updates (OTA), security and real-time constraints.",
      when: "Connected devices, wearables, industrial and automotive systems.",
      how: "Test on real hardware; cover connectivity loss, power states, OTA updates and edge cases.",
      tip: "Hardware-software integration and intermittent connectivity are the hardest, highest-value areas.",
      related: ["Security Testing", "Reliability Testing", "Compatibility Testing"] },
    { t: "Cookie / Session Testing", cat: "domain", d: "Verifying correct creation, expiry and handling of cookies and user sessions (timeouts, concurrent logins).",
      long: "Checks that cookies and sessions are created, scoped, secured and expired correctly — including timeouts, concurrent logins, logout and privacy/security flags.",
      when: "Web apps with authentication and stateful sessions.",
      how: "Inspect cookies (Secure/HttpOnly/SameSite), test timeouts, concurrent sessions and logout invalidation.",
      tip: "Session fixation and missing Secure/HttpOnly flags are common security findings here.",
      related: ["Security Testing", "GUI / UI Testing", "API Testing"] },
    { t: "Email / Notification Testing", cat: "domain", d: "Verifying transactional emails/push/SMS — triggers, content, links, rendering and deliverability.",
      long: "Validates that notifications fire on the right triggers, contain correct dynamic content and links, render across clients, and actually get delivered.",
      when: "Any product sending transactional emails, push or SMS.",
      how: "Trigger events; verify content, links, personalization, cross-client rendering and deliverability (spam).",
      tip: "Use mail-sink tools (Mailtrap) to assert content, and test rendering across major email clients.",
      related: ["Functional Testing", "API Testing", "Localization Testing (l10n)"] },
    { t: "Localization (Language) Testing", cat: "domain", d: "Verifying translated UIs render correctly without truncation, encoding or layout breakage.",
      long: "Focuses on the visual/linguistic correctness of localized builds: accurate translations in context, no truncation/overlap, correct encoding and right-to-left support.",
      when: "After translating UI for each target language.",
      how: "Native-speaker review in-context, plus checks for truncation, encoding and RTL layout.",
      tip: "Context matters — a word translated correctly in isolation can be wrong on a button.",
      related: ["Localization Testing (l10n)", "Internationalization Testing (i18n)", "GUI / UI Testing"] },
  ];

  window.QA_TYPES = { categories, types };
})();
